name: getting-started

on: [push]

jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: firststep
        run: echo "first step has been triggered"
      - name: readrepodata
        uses: actions/checkout@v2
      - name: use-python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: execute_my_py_script # run the run.py to get the latest data
        run: |
          python getting_started.py
      - name: listdata_in_repo
        run: |
          pwd
          ls